version: "3"
services:
  on_services:
    image: registry.stardev.space/on_services:latest
    restart: always
    container_name: on_services
    env_file:
      - .env
    ports:
      - "3000:3000"